### ISSUE TITLE
WalletsIn.java:79-82: Read instance of the Wallet from...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/java-api#13]
The puzzle `4-aab61a84` from #4 has to be resolved:

https://github.com/zold-io/java-api/blob/93fa5fc251ff69dcb28db1b9a5195c111b05c004/src/main/java/io/zold/api/WalletsIn.java#L79-L82

The puzzle was created by Tolegen Izbassar on 03-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
I can't create GitHub labels `pdd`. Most likely I don't have necessary permissions to `zold-io/java-api` repository. Please, make sure @0pdd user is in the [list of collaborators](https://github.com/zold-io/java-api/settings/collaboration):

```Octokit::NotFound
POST https://api.github.com/repos/zold-io/java-api/labels: 404 - Not Found // See: https://developer.github.com/v3/issues/labels/#create-a-label
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:9:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:61:in `on_complete'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/connection.rb:175:in `post'
/app/vendor/bundle/ruby/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/connection.rb:156:in `request'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/connection.rb:28:in `post'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/client/labels.rb:44:in `add_label'
/app/objects/github_tagged_tickets.rb:50:in `block in submit'
/app/objects/github_tagged_tickets.rb:50:in `each'
/app/objects/github_tagged_tickets.rb:50:in `submit'
/app/objects/commit_tickets.rb:38:in `submit'
/app/objects/emailed_tickets.rb:35:in `submit'
/app/objects/sentry_tickets.rb:46:in `submit'
/app/objects/puzzles.rb:91:in `block in expose'
/app/objects/puzzles.rb:82:in `loop'
/app/objects/puzzles.rb:82:in `expose'
/app/objects/puzzles.rb:33:in `deploy'
/app/objects/job.rb:38:in `proceed'
/app/objects/job_starred.rb:33:in `proceed'
/app/objects/job_recorded.rb:32:in `proceed'
/app/objects/job_emailed.rb:35:in `proceed'
/app/objects/job_commiterrors.rb:36:in `proceed'
/app/objects/job_detached.rb:48:in `exclusive'
/app/objects/job_detached.rb:36:in `block in proceed'
/app/objects/job_detached.rb:36:in `fork'
/app/objects/job_detached.rb:36:in `proceed'
/app/0pdd.rb:342:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `block in compile!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1011:in `route_eval'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1039:in `block in process_route'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `process_route'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:990:in `block in route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1096:in `block in dispatch!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1093:in `dispatch!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/xss_header.rb:18:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/path_traversal.rb:16:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/json_csrf.rb:26:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/frame_options.rb:31:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/logger.rb:15:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/common_logger.rb:33:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:231:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:224:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1728:in `synchronize'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6ac9e0a3-eadb-45bf-b051-800033971ed4, thread: pool-618-thread-1
com.zerocracy.radars.github.ThrottledComments[76] java.lang.IllegalStateException: Can't post an identical message to zold-io/java-api#13: @llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue
```

[0.24.9](https://github.com/zerocracy/farm): Issue: zold-io/java-api#13, Action: `opened`

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zold-io/java-api/issues/13#issuecomment-402844561))

@llorllale Job [#13](https://github.com/zold-io/java-api/issues/13) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#13](https://github.com/zold-io/java-api/issues/13) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/CAZUREFND/1862057162); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zold-io/java-api/issues/13#issuecomment-402882379))

@llorllale The user @llorllale[/z](https://www.0crat.com/u/llorllale) resigned from [#13](https://github.com/zold-io/java-api/issues/13), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#13](https://github.com/zold-io/java-api/issues/13) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CAZUREFND/1911448391); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@llorllale see PR #37 please

**Comment by carlosmiranda** [comment]
@0crat wait for merge of PR #37.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@d5919f8f-70fb-4d83-b171-c98b23ac0383, thread: pool-75-thread-1
com.zerocracy.pm.Claims[109] java.lang.IllegalStateException: Duplicate claims are not allowed in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), can't add this XML to 4 existing ones (Add job to WBS;{job=gh:zold-io/java-api#37, role=REV};github;zold-io/java-api;37,Add job to WBS;{job=gh:zold-io/java-api#37, role=REV};github;zold-io/java-api;37,Register impediment;{comment=404983211, job=gh:zold-io/java-api#13, issue=13, repo=zold-io/java-api};github;zold-io/java-api;13;404983211,Start order;{cause=1942014085, reason=@carlosmiranda (13.89 of 15):
  +-0.00 9 jobs in the agenda, still enough room (max is 32)
  +4.00=1.00x4 Reputation +1845 jobs is no.1
  +-0.00 Reputation +1845 is above -128
  +2.00=1.00x2 Hourly rate $30.00 is no.1
  +-0.00 The debt is absent or small enough
  +-0.00 There are no bans in [#36](https://github.com/zold-io/java-api/issues/36)
  +-0.00 The user is not on vacation
  +1.00 Workload of 9 jobs is no.1
  +1.00 Workload of 3 jobs is no.1
  +3.00=1.00x3 Average delivery time 9days is no.1
  +2.00=0.67x3 Has 9 jobs in 7 projects, 0.33% from current project
  +0.89 Entropy, job=gh:zold-io/java-api#36, login=carlosmiranda, public=true, flow=Ping};job;gh:zold-io/java-api#36):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1950010011">
   <created>2018-07-14T00:10:51.914Z</created>
   <type>Register impediment</type>
   <token>github;zold-io/java-api;13;404983211</token>
   <author>carlosmiranda</author>
   <params>
      <param name="job">gh:zold-io/java-api#13</param>
      <param name="repo">zold-io/java-api</param>
      <param name="issue">13</param>
      <param name="comment">404983211</param>
   </params>
</claim>

```

[0.25.9](https://github.com/zerocracy/farm): Issue: zold-io/java-api#13, Comment: 404983211

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@d5919f8f-70fb-4d83-b171-c98b23ac0383, thread: pool-75-thread-1
com.zerocracy.radars.github.ReSafe[78] java.io.IOException: java.lang.IllegalStateException: Duplicate claims are not allowed in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), can't add this XML to 4 existing ones (Add job to WBS;{job=gh:zold-io/java-api#37, role=REV};github;zold-io/java-api;37,Add job to WBS;{job=gh:zold-io/java-api#37, role=REV};github;zold-io/java-api;37,Register impediment;{comment=404983211, job=gh:zold-io/java-api#13, issue=13, repo=zold-io/java-api};github;zold-io/java-api;13;404983211,Start order;{cause=1942014085, reason=@carlosmiranda (13.89 of 15):
  +-0.00 9 jobs in the agenda, still enough room (max is 32)
  +4.00=1.00x4 Reputation +1845 jobs is no.1
  +-0.00 Reputation +1845 is above -128
  +2.00=1.00x2 Hourly rate $30.00 is no.1
  +-0.00 The debt is absent or small enough
  +-0.00 There are no bans in [#36](https://github.com/zold-io/java-api/issues/36)
  +-0.00 The user is not on vacation
  +1.00 Workload of 9 jobs is no.1
  +1.00 Workload of 3 jobs is no.1
  +3.00=1.00x3 Average delivery time 9days is no.1
  +2.00=0.67x3 Has 9 jobs in 7 projects, 0.33% from current project
  +0.89 Entropy, job=gh:zold-io/java-api#36, login=carlosmiranda, public=true, flow=Ping};job;gh:zold-io/java-api#36):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1950010011">
   <created>2018-07-14T00:10:51.914Z</created>
   <type>Register impediment</type>
   <token>github;zold-io/java-api;13;404983211</token>
   <author>carlosmiranda</author>
   <params>
      <param name="job">gh:zold-io/java-api#13</param>
      <param name="repo">zold-io/java-api</param>
      <param name="issue">13</param>
      <param name="comment">404983211</param>
   </params>
</claim>

com.zerocracy.pm.Claims[109] java.lang.IllegalStateException: Duplicate claims are not allowed in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), can't add this XML to 4 existing ones (Add job to WBS;{job=gh:zold-io/java-api#37, role=REV};github;zold-io/java-api;37,Add job to WBS;{job=gh:zold-io/java-api#37, role=REV};github;zold-io/java-api;37,Register impediment;{comment=404983211, job=gh:zold-io/java-api#13, issue=13, repo=zold-io/java-api};github;zold-io/java-api;13;404983211,Start order;{cause=1942014085, reason=@carlosmiranda (13.89 of 15):
  +-0.00 9 jobs in the agenda, still enough room (max is 32)
  +4.00=1.00x4 Reputation +1845 jobs is no.1
  +-0.00 Reputation +1845 is above -128
  +2.00=1.00x2 Hourly rate $30.00 is no.1
  +-0.00 The debt is absent or small enough
  +-0.00 There are no bans in [#36](https://github.com/zold-io/java-api/issues/36)
  +-0.00 The user is not on vacation
  +1.00 Workload of 9 jobs is no.1
  +1.00 Workload of 3 jobs is no.1
  +3.00=1.00x3 Average delivery time 9days is no.1
  +2.00=0.67x3 Has 9 jobs in 7 projects, 0.33% from current project
  +0.89 Entropy, job=gh:zold-io/java-api#36, login=carlosmiranda, public=true, flow=Ping};job;gh:zold-io/java-api#36):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1950010011">
   <created>2018-07-14T00:10:51.914Z</created>
   <type>Register impediment</type>
   <token>github;zold-io/java-api;13;404983211</token>
   <author>carlosmiranda</author>
   <params>
      <param name="job">gh:zold-io/java-api#13</param>
      <param name="repo">zold-io/java-api</param>
      <param name="issue">13</param>
      <param name="comment">404983211</param>
   </params>
</claim>

```

[0.25.9](https://github.com/zerocracy/farm): Issue: zold-io/java-api#13, Action: `created`

**Comment by carlosmiranda** [comment]
@0crat wait for merge of PR #37

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@d5919f8f-70fb-4d83-b171-c98b23ac0383, thread: pool-90-thread-1
com.zerocracy.pm.Claims[109] java.lang.IllegalStateException: Duplicate claims are not allowed in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), can't add this XML to 5 existing ones (Add job to WBS;{job=gh:zold-io/java-api#37, role=REV};github;zold-io/java-api;37,Add job to WBS;{job=gh:zold-io/java-api#37, role=REV};github;zold-io/java-api;37,Register impediment;{comment=404983211, job=gh:zold-io/java-api#13, issue=13, repo=zold-io/java-api};github;zold-io/java-api;13;404983211,Register impediment;{comment=404983753, job=gh:zold-io/java-api#13, issue=13, repo=zold-io/java-api};github;zold-io/java-api;13;404983753,Start order;{cause=1942014085, reason=@carlosmiranda (13.89 of 15):
  +-0.00 9 jobs in the agenda, still enough room (max is 32)
  +4.00=1.00x4 Reputation +1845 jobs is no.1
  +-0.00 Reputation +1845 is above -128
  +2.00=1.00x2 Hourly rate $30.00 is no.1
  +-0.00 The debt is absent or small enough
  +-0.00 There are no bans in [#36](https://github.com/zold-io/java-api/issues/36)
  +-0.00 The user is not on vacation
  +1.00 Workload of 9 jobs is no.1
  +1.00 Workload of 3 jobs is no.1
  +3.00=1.00x3 Average delivery time 9days is no.1
  +2.00=0.67x3 Has 9 jobs in 7 projects, 0.33% from current project
  +0.89 Entropy, job=gh:zold-io/java-api#36, login=carlosmiranda, public=true, flow=Ping};job;gh:zold-io/java-api#36):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1950016012">
   <created>2018-07-14T00:16:45.61Z</created>
   <type>Register impediment</type>
   <token>github;zold-io/java-api;13;404983753</token>
   <author>carlosmiranda</author>
   <params>
      <param name="job">gh:zold-io/java-api#13</param>
      <param name="repo">zold-io/java-api</param>
      <param name="issue">13</param>
      <param name="comment">404983753</param>
   </params>
</claim>

```

[0.25.9](https://github.com/zerocracy/farm): Issue: zold-io/java-api#13, Comment: 404983753

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@d5919f8f-70fb-4d83-b171-c98b23ac0383, thread: pool-90-thread-1
com.zerocracy.radars.github.ReSafe[78] java.io.IOException: java.lang.IllegalStateException: Duplicate claims are not allowed in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), can't add this XML to 5 existing ones (Add job to WBS;{job=gh:zold-io/java-api#37, role=REV};github;zold-io/java-api;37,Add job to WBS;{job=gh:zold-io/java-api#37, role=REV};github;zold-io/java-api;37,Register impediment;{comment=404983211, job=gh:zold-io/java-api#13, issue=13, repo=zold-io/java-api};github;zold-io/java-api;13;404983211,Register impediment;{comment=404983753, job=gh:zold-io/java-api#13, issue=13, repo=zold-io/java-api};github;zold-io/java-api;13;404983753,Start order;{cause=1942014085, reason=@carlosmiranda (13.89 of 15):
  +-0.00 9 jobs in the agenda, still enough room (max is 32)
  +4.00=1.00x4 Reputation +1845 jobs is no.1
  +-0.00 Reputation +1845 is above -128
  +2.00=1.00x2 Hourly rate $30.00 is no.1
  +-0.00 The debt is absent or small enough
  +-0.00 There are no bans in [#36](https://github.com/zold-io/java-api/issues/36)
  +-0.00 The user is not on vacation
  +1.00 Workload of 9 jobs is no.1
  +1.00 Workload of 3 jobs is no.1
  +3.00=1.00x3 Average delivery time 9days is no.1
  +2.00=0.67x3 Has 9 jobs in 7 projects, 0.33% from current project
  +0.89 Entropy, job=gh:zold-io/java-api#36, login=carlosmiranda, public=true, flow=Ping};job;gh:zold-io/java-api#36):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1950016012">
   <created>2018-07-14T00:16:45.61Z</created>
   <type>Register impediment</type>
   <token>github;zold-io/java-api;13;404983753</token>
   <author>carlosmiranda</author>
   <params>
      <param name="job">gh:zold-io/java-api#13</param>
      <param name="repo">zold-io/java-api</param>
      <param name="issue">13</param>
      <param name="comment">404983753</param>
   </params>
</claim>

com.zerocracy.pm.Claims[109] java.lang.IllegalStateException: Duplicate claims are not allowed in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), can't add this XML to 5 existing ones (Add job to WBS;{job=gh:zold-io/java-api#37, role=REV};github;zold-io/java-api;37,Add job to WBS;{job=gh:zold-io/java-api#37, role=REV};github;zold-io/java-api;37,Register impediment;{comment=404983211, job=gh:zold-io/java-api#13, issue=13, repo=zold-io/java-api};github;zold-io/java-api;13;404983211,Register impediment;{comment=404983753, job=gh:zold-io/java-api#13, issue=13, repo=zold-io/java-api};github;zold-io/java-api;13;404983753,Start order;{cause=1942014085, reason=@carlosmiranda (13.89 of 15):
  +-0.00 9 jobs in the agenda, still enough room (max is 32)
  +4.00=1.00x4 Reputation +1845 jobs is no.1
  +-0.00 Reputation +1845 is above -128
  +2.00=1.00x2 Hourly rate $30.00 is no.1
  +-0.00 The debt is absent or small enough
  +-0.00 There are no bans in [#36](https://github.com/zold-io/java-api/issues/36)
  +-0.00 The user is not on vacation
  +1.00 Workload of 9 jobs is no.1
  +1.00 Workload of 3 jobs is no.1
  +3.00=1.00x3 Average delivery time 9days is no.1
  +2.00=0.67x3 Has 9 jobs in 7 projects, 0.33% from current project
  +0.89 Entropy, job=gh:zold-io/java-api#36, login=carlosmiranda, public=true, flow=Ping};job;gh:zold-io/java-api#36):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1950016012">
   <created>2018-07-14T00:16:45.61Z</created>
   <type>Register impediment</type>
   <token>github;zold-io/java-api;13;404983753</token>
   <author>carlosmiranda</author>
   <params>
      <param name="job">gh:zold-io/java-api#13</param>
      <param name="repo">zold-io/java-api</param>
      <param name="issue">13</param>
      <param name="comment">404983753</param>
   </params>
</claim>

```

[0.25.9](https://github.com/zerocracy/farm): Issue: zold-io/java-api#13, Action: `created`

**Comment by 0crat** [comment]
> @0crat wait for merge of PR #37. ([here](https://github.com/zold-io/java-api/issues/13#issuecomment-404983211))

@carlosmiranda The impediment for [#13](https://github.com/zold-io/java-api/issues/13) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
> @0crat wait for merge of PR #37 ([here](https://github.com/zold-io/java-api/issues/13#issuecomment-404983753))

@carlosmiranda Job [#13](https://github.com/zold-io/java-api/issues/13) is already on hold

**Comment by 0pdd** [comment]
The puzzle `4-aab61a84` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6ac5f120-3284-4029-a28e-e08780c3ba80, thread: pool-88-thread-1
com.zerocracy.pm.Claims[109] java.lang.IllegalStateException: Duplicate claims are not allowed in [CAZUREFND](https://www.0crat.com/p/CAZUREFND), can't add this XML to 9 existing ones (Award points were added;{reason=Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28), minutes=10, cause=1971338583, job=gh:zold-io/java-api#36, login=llorllale, age=3612, flow=Close job; Finish order; Order was finished; Make payment, points=10};github;zold-io/java-api;36,Close job;{job=gh:zold-io/java-api#13, reason=GitHub issue was closed};github;zold-io/java-api;13,Close job;{job=gh:zold-io/java-api#13, reason=GitHub issue was closed};github;zold-io/java-api;13,Job removed from WBS;{reason=Job was closed, order is finished, cause=1971338585, job=gh:zold-io/java-api#36, login=carlosmiranda, age=3612, flow=Close job; Finish order; Order was finished; Remove job from WBS};github;zold-io/java-api;36,Notify project;{reason=Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28), minutes=10, cause=1971338583, job=gh:zold-io/java-api#36, login=llorllale, message=We just paid $5.33 to @llorllale[/z](https://www.0crat.com/u/llorllale)[/z](https://www.0crat.com/u/llorllale) for [#36](https://github.com/zold-io/java-api/issues/36): Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28), age=3612, flow=Close job; Finish order; Order was finished; Make payment};github;zold-io/java-api;36,Notify user;{reason=Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28), minutes=10, cause=1971338583, job=gh:zold-io/java-api#36, login=llorllale, message=We are very sorry, but we failed to pay you $5.33 for [#36](https://github.com/zold-io/java-api/issues/36): "The amount $5.33 is too small at: Payment for [#36](https://github.com/zold-io/java-api/issues/36) (10 minutes): Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28)"; this amount was added to the list of payments we owe you; we will try to send them all together very soon; we will keep you informed, see [§20](http://www.zerocracy.com/policy.html#20), age=3612, flow=Close job; Finish order; Order was finished; Make payment};user;llorllale,Notify;{reason=Job was closed, order is finished, cause=1971338585, job=gh:zold-io/java-api#36, login=carlosmiranda, message=The job [#36](https://github.com/zold-io/java-api/issues/36) is now out of scope, age=3612, flow=Close job; Finish order; Order was finished; Remove job from WBS};github;zold-io/java-api;36,Payment was added to debts;{reason=Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28), amount=$5.33, minutes=10, cause=1971338583, job=gh:zold-io/java-api#36, login=llorllale, age=3612, flow=Close job; Finish order; Order was finished; Make payment};github;zold-io/java-api;36,Send zold;{reason=Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28), amount=$5.33, minutes=10, recipient=llorllale, cause=1971338583, job=gh:zold-io/java-api#36, login=llorllale, age=3612, flow=Close job; Finish order; Order was finished; Make payment};github;zold-io/java-api;36):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1971338595">
   <created>2018-07-16T13:38:36.889Z</created>
   <type>Close job</type>
   <token>github;zold-io/java-api;13</token>
   <author>0pdd</author>
   <params>
      <param name="job">gh:zold-io/java-api#13</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-07-16T13:53:36.891Z</until>
</claim>

```

[0.25.15](https://github.com/zerocracy/farm): Issue: zold-io/java-api#13, Action: `closed`

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#13](https://github.com/zold-io/java-api/issues/13) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +46 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
