### ISSUE TITLE
RtTransaction.java:53-55: Implement id() by parsing the...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/java-api#22]
The puzzle `15-4f67a35d` from #15 has to be resolved:

https://github.com/zold-io/java-api/blob/1405fe34b5be0e02132acb21aae7102e3d57bc2f/src/main/java/io/zold/api/RtTransaction.java#L53-L55

The puzzle was created by Tolegen Izbassar on 06-Jul-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
I can't create GitHub labels `pdd`. Most likely I don't have necessary permissions to `zold-io/java-api` repository. Please, make sure @0pdd user is in the [list of collaborators](https://github.com/zold-io/java-api/settings/collaboration):

```Octokit::NotFound
POST https://api.github.com/repos/zold-io/java-api/labels: 404 - Not Found // See: https://developer.github.com/v3/issues/labels/#create-a-label
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:9:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:61:in `on_complete'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'
/app/vendor/bundle/ruby/2.3.0/gems/faraday-0.15.2/lib/faraday/connection.rb:175:in `post'
/app/vendor/bundle/ruby/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/connection.rb:156:in `request'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/connection.rb:28:in `post'
/app/vendor/bundle/ruby/2.3.0/gems/octokit-4.9.0/lib/octokit/client/labels.rb:44:in `add_label'
/app/objects/github_tagged_tickets.rb:50:in `block in submit'
/app/objects/github_tagged_tickets.rb:50:in `each'
/app/objects/github_tagged_tickets.rb:50:in `submit'
/app/objects/commit_tickets.rb:38:in `submit'
/app/objects/emailed_tickets.rb:35:in `submit'
/app/objects/sentry_tickets.rb:46:in `submit'
/app/objects/puzzles.rb:91:in `block in expose'
/app/objects/puzzles.rb:82:in `loop'
/app/objects/puzzles.rb:82:in `expose'
/app/objects/puzzles.rb:33:in `deploy'
/app/objects/job.rb:38:in `proceed'
/app/objects/job_starred.rb:33:in `proceed'
/app/objects/job_recorded.rb:32:in `proceed'
/app/objects/job_emailed.rb:35:in `proceed'
/app/objects/job_commiterrors.rb:36:in `proceed'
/app/objects/job_detached.rb:48:in `exclusive'
/app/objects/job_detached.rb:36:in `block in proceed'
/app/objects/job_detached.rb:36:in `fork'
/app/objects/job_detached.rb:36:in `proceed'
/app/0pdd.rb:342:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `block in compile!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1011:in `route_eval'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1039:in `block in process_route'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `process_route'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:990:in `block in route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `route!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1096:in `block in dispatch!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1093:in `dispatch!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/xss_header.rb:18:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/path_traversal.rb:16:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/json_csrf.rb:26:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/frame_options.rb:31:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/logger.rb:15:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/common_logger.rb:33:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:231:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:224:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `block in call'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1728:in `synchronize'
/app/vendor/bundle/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/app/vendor/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@b6490ca6-870d-4128-afbc-1209b46d81f0, thread: pool-43-thread-1
com.zerocracy.radars.github.ThrottledComments[76] java.lang.IllegalStateException: Can't post an identical message to zold-io/java-api#22: @llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue
```

[0.25.5](https://github.com/zerocracy/farm): Issue: zold-io/java-api#22, Action: `opened`

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zold-io/java-api/issues/22#issuecomment-403839704))

@llorllale Job [#22](https://github.com/zold-io/java-api/issues/22) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#22](https://github.com/zold-io/java-api/issues/22) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CAZUREFND/2030658840); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@llorllale PR #47 is now available for this.

**Comment by carlosmiranda** [comment]
@0crat wait for merge of #47,

**Comment by 0crat** [comment]
> @0crat wait for merge of #47, ([here](https://github.com/zold-io/java-api/issues/22#issuecomment-406856213))

@carlosmiranda The impediment for [#22](https://github.com/zold-io/java-api/issues/22) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0pdd** [comment]
The puzzle `15-4f67a35d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@22c62a87-9c9e-4ad2-adbe-8ced5cbfe80b, thread: pool-25-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-02T15:50:51.012Z"
```

[0.28.8](https://github.com/zerocracy/farm): Issue: zold-io/java-api#22, Action: `closed`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@22c62a87-9c9e-4ad2-adbe-8ced5cbfe80b, thread: pool-24-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-02T15:50:57.477Z"
```

[0.28.8](https://github.com/zerocracy/farm): Issue: zold-io/java-api#22, Action: `closed`

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zold-io/java-api/issues/22#issuecomment-410098045))

@llorllale Job [#22](https://github.com/zold-io/java-api/issues/22) is not in the agenda of @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), can't inspect

**Comment by carlosmiranda** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zold-io/java-api/issues/22#issuecomment-410098045))

@llorllale The job [#22](https://github.com/zold-io/java-api/issues/22) is now out of scope

**Comment by carlosmiranda** [comment]
@ypshenychka @llorllale seems like `@0crat` got confused here, this is currently awaiting QA verdict.

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zold-io/java-api/issues/22#issuecomment-410116144); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
